import React from 'react';
import { View, Text, ScrollView, StyleSheet, SafeAreaView, Linking } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const InfoSection: React.FC<{ title: string; icon: keyof typeof Ionicons.glyphMap; children: React.ReactNode }> = ({ title, icon, children }) => (
  <View style={styles.section}>
    <View style={styles.sectionHeader}>
      <Ionicons name={icon} size={24} color="#333" />
      <Text style={styles.sectionTitle}>{title}</Text>
    </View>
    {children}
  </View>
);

export default function InfoPage() {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Text style={styles.pageTitle}>Important Information</Text>

        <InfoSection title="AI-Generated Content" icon="bulb-outline">
          <Text style={styles.text}>
            All food-related and nutrition-related information provided in this app is generated by artificial intelligence. While we strive for accuracy, this information should not be considered as professional medical advice.
          </Text>
        </InfoSection>

        <InfoSection title="Consult a Professional" icon="medical-outline">
          <Text style={styles.text}>
            If you have any concerns about your diet, nutrition, or health, we strongly recommend consulting with a qualified healthcare professional or registered dietitian.
          </Text>
        </InfoSection>

        <InfoSection title="Data Storage" icon="server-outline">
          <Text style={styles.text}>
            We prioritize your privacy. The only information stored in our database is:
          </Text>
          <Text style={styles.listItem}>• Your nutrition profile</Text>
          <Text style={styles.listItem}>• Login information</Text>
          <Text style={styles.listItem}>• Your food photos</Text>
          <Text style={styles.text}>
            No other personal data or food-related information is permanently stored by the app.
          </Text>
        </InfoSection>

        <InfoSection title="App Permissions" icon="key-outline">
          <Text style={styles.text}>
            This app requires certain permissions to function properly:
          </Text>
          <Text style={styles.listItem}>• Camera: Used to scan food items and generate nutritional information</Text>
          <Text style={styles.listItem}>• Storage: Required to save temporary data for app functionality</Text>
          <Text style={styles.text}>
            We do not access or use these permissions for any purpose other than the stated functionality of the app.
          </Text>
        </InfoSection>

        <InfoSection title="Camera Usage" icon="camera-outline">
          <Text style={styles.text}>
            The camera is used solely for scanning food items to generate nutritional information. Images are processed in real-time and are not stored or transmitted elsewhere.
          </Text>
        </InfoSection>

        <InfoSection title="Privacy & Security" icon="shield-checkmark-outline">
          <Text style={styles.text}>
            We are committed to protecting your privacy and ensuring the security of any data you provide.
          </Text>
        </InfoSection>

        <Text style={styles.footer} dataDetectorType="email">
          If you have any questions or concerns, please contact <Text style={{
            color:"black"
          }} onPress={()=>{
            Linking.openURL("mailto:sharmavipul01002@gmail.com")
          }}>sharmavipul01002@gmail.com</Text>
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContent: {
    padding: 20,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginLeft: 10,
  },
  text: {
    fontSize: 16,
    color: '#444',
    lineHeight: 24,
    marginBottom: 10,
  },
  listItem: {
    fontSize: 16,
    color: '#444',
    lineHeight: 24,
    marginLeft: 10,
    marginBottom: 5,
  },
  footer: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 20,
    fontStyle: 'italic',
  },
});

